### ISSUE TITLE
Brazilian Portuguese isn't enabled as a language (yet)

### ISSUE THREAD

**Issue by contraexemplo** [infuse-l10n-pt-br/Infuse#2]
Issue #1 listed all files needed to create a Brazilian Portuguese translation of the Malicious Infrastructure learning path. It included configuration files because this is the first Brazilian Portuguese translation of a learning path — Brazilian Portuguese isn't enabled as a language on the Infuse website (yet).

That will require us to do the following:  

- Create a `pt-br.yml` under `i18n/`:

```
Infuse/
├── archetypes/
├── assets/
├── content/
├── i18n/
│   └── pt-br.yml
├── layouts/
├── learner-assets/
├── static/
└── hugo.toml
```
- Translate every i18n key added to `pt-br.yml`.

- Make the following changes to Infuse's configuration file, `hugo.toml`:

```toml
  [languages.pt-br]
  languageName = "Brazilian Portuguese"
  weight    = 5
  [languages.pt-br.params]
    languageName = "Brazilian Portuguese"
    direction = "ltr"
```
